### ISSUE TITLE
ImageDataGenerator 

### ISSUE THREAD

**Issue by hackgoofer** [wassname/pipe-segmentation#1]
Hi, I don't think the following code guarantees that the dategen1 and datagen2 are the same data augmentation transformations. 

According to the [Keras source code](https://github.com/fchollet/keras/blob/d92fab69a253db150af9d3fd638f2a01d53f4aa9/keras/preprocessing/image.py), there is a concept of randomization here. 

For the segmentation to work, you need the guarantee that the original image and its masks are augmented the same way, which I think you are not doing it here with the following code:
```
data_gen_args=dict(
                rotation_range=10.,
                width_shift_range=0.1,
                height_shift_range=0.1,
                shear_range=np.deg2rad(10),
                zoom_range=0.1,
                channel_shift_range=0.01,
                fill_mode='constant',
                horizontal_flip=True,
                vertical_flip=True,
                rescale=1/255.
)

datagen1 = ImageDataGenerator(**data_gen_args)
datagen2 = ImageDataGenerator(**data_gen_args)

image_gen=datagen1.flow_from_directory(dest_dir, 
                                  class_mode=None, 
                                  classes=['image'], 
                                  batch_size=batch_size, 
                                  seed=seed,
                                  target_size=output_shape,
                                 )
mask_gen=datagen2.flow_from_directory(dest_dir, 
                                  class_mode=None, 
                                  classes=['mask'], 
                                  batch_size=batch_size, 
                                  seed=seed,
                                  target_size=output_shape,
                                 )

```

Please let me know what you think, happy to know I could be wrong as well. This specific problem is discussed in further detail here as well: https://github.com/fchollet/keras/issues/3338

**Comment by wassname** [comment]
Hi ytshent, yeah you're right. And I thought about this too, so I made a PR to make ImageDataGenerator repeatable. The PR was accepted into keras (https://github.com/fchollet/keras/pull/3751). I had a unit test to make sure but it wasn't accepted into the repo, but it was fully repeatable right after my PR was merged.

**Comment by hackgoofer** [comment]
Ah, awesome to know. I will test it out. Thank you.

**Comment by wassname** [comment]
No problems, [here](https://github.com/wassname/keras/blob/d37583e32191ac4cc42c131926bbd38cabd13b6f/tests/keras/preprocessing/test_image.py#L93) is my unit test if that helps you.
