### ISSUE TITLE
keras version incompatibility

### ISSUE THREAD

**Issue by ramdhan1989** [wassname/pipe-segmentation#2]
Is there any update code using latest keras ? I got so many errors due to keras version incompatibility. This is really good project, I have similar project that need pipeline segmentations. If I want to train using my own dataset, how to configure the data input and label ? 

Thank you

**Comment by wassname** [comment]
Thanks. Unfortunately, No there isn't as I haven't worked on this in a while.

Keras has changed a lot in the last three years, so you could either start from a different repo, or use an old version of keras (which may be difficult with modern GPU drivers).
